// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM97NuYztefohKu9DKbkOLlIsAawAswG8',
    appId: '1:658104141431:web:d899b54bc1405c88166872',
    messagingSenderId: '658104141431',
    projectId: 'telelite-48c4b',
    authDomain: 'telelite-48c4b.firebaseapp.com',
    storageBucket: 'telelite-48c4b.firebasestorage.app',
    measurementId: 'G-V891GHCMXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmxlZSjM3oh2nlute7ze1zPqaau8VnSFs',
    appId: '1:658104141431:android:58195493d7a7303c166872',
    messagingSenderId: '658104141431',
    projectId: 'telelite-48c4b',
    storageBucket: 'telelite-48c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7FaAAk6mI3CIpFcejea6knWGD2hbNsqE',
    appId: '1:658104141431:ios:1a2a4bfae143572c166872',
    messagingSenderId: '658104141431',
    projectId: 'telelite-48c4b',
    storageBucket: 'telelite-48c4b.firebasestorage.app',
    iosBundleId: 'com.example.telegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM97NuYztefohKu9DKbkOLlIsAawAswG8',
    appId: '1:658104141431:web:6e6b421c317e4245166872',
    messagingSenderId: '658104141431',
    projectId: 'telelite-48c4b',
    authDomain: 'telelite-48c4b.firebaseapp.com',
    storageBucket: 'telelite-48c4b.firebasestorage.app',
    measurementId: 'G-ZEQSFWMP9H',
  );
}
